# Generated by Django 4.1.2 on 2022-11-10 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_interested'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client'},
        ),
    ]
