# Generated by Django 4.1.2 on 2022-11-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_client_interested_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_image/profile.png', upload_to='profile_images/'),
        ),
    ]
